Create histogram for numerical column.
Create boxplot for outlier detection.
Create scatter plot for relationships.
Create correlation heatmap.
Create bar chart for categorical data.
Plot pairwise relationships.
Plot distribution of ages.
Visualize missing values.
Compare categories visually.
Analyze trends using line charts.
Advanced Beginner EDA
Perform complete EDA on Titanic dataset.
Perform EDA on sales dataset.
Analyze student performance dataset.
Analyze COVID dataset.
Analyze employee salary dataset.
Detect skewness in dataset.
Create pivot tables for analysis.
Analyze time-series dataset basics.
Create EDA report summary.
Build complete preprocessing + EDA workflow.

In [2]:
import pandas as pd 
import numpy as np

In [3]:
#Load dataset using pandas.
data=pd.read_csv('dataset.csv')

In [4]:
#Display first 5 rows of dataset.
data.head()

,Student_ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
0,1,Female,19,Mardan,CS,5,1056,879,41,2.98,...,Yes,No,High,Bike,4,Good,99,27,2,Placed
1,2,Female,19,Mardan,IT,7,622,973,88,2.84,...,Yes,No,Low,Car,4,Good,38,29,5,Placed
2,3,Female,21,Mardan,DS,2,836,794,64,3.97,...,Yes,Yes,High,Bike,6,Average,81,25,5,Placed
3,4,Female,21,Abbottabad,DS,7,670,860,93,1.73,...,No,No,High,Bus,2,Good,79,43,4,Placed
4,5,Male,19,Peshawar,DS,7,734,1097,94,3.40,...,No,No,Low,Bus,6,Fluent,50,3,1,Placed

In [5]:
#Display last 5 rows of dataset.
data.tail()

,Student_ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
9995,9996,Female,18,Abbottabad,AI,2,713,711,60,1.93,...,No,No,Middle,Walk,8,Good,75,39,4,Placed
9996,9997,Male,19,Karachi,IT,8,807,689,33,1.96,...,Yes,No,High,Bus,4,Average,59,13,2,Placed
9997,9998,Female,26,Karachi,ME,6,1085,661,75,2.72,...,Yes,No,Low,Bike,2,Weak,99,47,1,Placed
9998,9999,Female,25,Abbottabad,DS,4,764,718,58,3.88,...,Yes,Yes,High,Walk,7,Average,41,1,5,Placed
9999,10000,Male,21,Karachi,ME,6,1058,835,99,3.20,...,No,No,Middle,Bike,4,Good,58,11,1,Placed

In [6]:
#Check dataset shape.
data.shape

(10000, 38)

In [7]:
#Check dataset columns.
data.columns

Index(['Student_ID', 'Gender', 'Age', 'City', 'Department', 'Semester',
       'Matric_Marks', 'Intermediate_Marks', 'Entry_Test_Score',
       'Current_CGPA', 'Previous_Semester_GPA', 'Attendance_Percentage',
       'Study_Hours_Per_Day', 'Sleep_Hours', 'Social_Media_Hours',
       'Stress_Level', 'Motivation_Level', 'Discipline_Level',
       'Programming_Skill_Level', 'Python_Knowledge', 'Java_Knowledge',
       'Database_Knowledge', 'ML_Knowledge', 'Web_Development_Skill',
       'GitHub_Projects_Count', 'Certifications_Count',
       'Internship_Experience', 'Internship_Duration_Months', 'Scholarship',
       'Hostel_Resident', 'Financial_Background', 'Transport_Mode',
       'Communication_Skill', 'English_Level', 'Resume_Score',
       'Job_Applications_Submitted', 'Offer_Letters_Received',
       'Placement_Status'],
      dtype='str')

In [8]:
#Check datatypes of columns.
data.dtypes

Student_ID                      int64
Gender                            str
Age                             int64
City                              str
Department                        str
Semester                        int64
Matric_Marks                    int64
Intermediate_Marks              int64
Entry_Test_Score                int64
Current_CGPA                  float64
Previous_Semester_GPA         float64
Attendance_Percentage           int64
Study_Hours_Per_Day           float64
Sleep_Hours                   float64
Social_Media_Hours            float64
Stress_Level                      str
Motivation_Level                  str
Discipline_Level                  str
Programming_Skill_Level           str
Python_Knowledge                int64
Java_Knowledge                  int64
Database_Knowledge              int64
ML_Knowledge                    int64
Web_Development_Skill           int64
GitHub_Projects_Count           int64
Certifications_Count            int64
Internship_Experience             str
Internship_Duration_Months      int64
Scholarship                       str
Hostel_Resident                   str
Financial_Background              str
Transport_Mode                    str
Communication_Skill             int64
English_Level                     str
Resume_Score                    int64
Job_Applications_Submitted      int64
Offer_Letters_Received          int64
Placement_Status                  str
dtype: object

In [9]:
#Generate summary statistics.
data.describe()

,Student_ID,Age,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,Previous_Semester_GPA,Attendance_Percentage,Study_Hours_Per_Day,...,Database_Knowledge,ML_Knowledge,Web_Development_Skill,GitHub_Projects_Count,Certifications_Count,Internship_Duration_Months,Communication_Skill,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received
count,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,21.980000,4.473600,846.30210,849.695200,64.484900,2.741796,2.732555,69.901000,4.279040,...,5.003900,5.044400,5.051300,9.915000,4.02670,3.312900,5.468500,65.094500,24.992300,2.50000
std,2886.89568,2.572637,2.295001,143.76455,143.507068,20.542443,0.725133,0.763340,17.672788,2.159642,...,3.158652,3.147478,3.160643,6.070507,2.60278,4.092563,2.877297,20.446579,14.796308,1.70132
min,1.00000,18.000000,1.000000,600.00000,600.000000,30.000000,1.500000,1.010000,40.000000,0.500000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,30.000000,0.000000,0.00000
25%,2500.75000,20.000000,2.000000,722.00000,727.750000,47.000000,2.110000,2.130000,55.000000,2.400000,...,2.000000,2.000000,2.000000,5.000000,2.00000,0.000000,3.000000,47.000000,12.000000,1.00000
50%,5000.50000,22.000000,4.000000,846.00000,849.000000,64.000000,2.740000,2.730000,70.000000,4.300000,...,5.000000,5.000000,5.000000,10.000000,4.00000,1.000000,5.000000,65.000000,25.000000,3.00000
75%,7500.25000,24.000000,6.000000,969.25000,972.000000,82.000000,3.370000,3.360000,85.000000,6.100000,...,8.000000,8.000000,8.000000,15.000000,6.00000,7.000000,8.000000,83.000000,38.000000,4.00000
max,10000.00000,26.000000,8.000000,1100.00000,1100.000000,100.000000,4.000000,4.000000,100.000000,8.000000,...,10.000000,10.000000,10.000000,20.000000,8.00000,12.000000,10.000000,100.000000,50.000000,5.00000

In [10]:
#Find missing values.
data.isnull()

,Student_ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
#Count total missing values.
data.isnull().sum()

Student_ID                    0
Gender                        0
Age                           0
City                          0
Department                    0
Semester                      0
Matric_Marks                  0
Intermediate_Marks            0
Entry_Test_Score              0
Current_CGPA                  0
Previous_Semester_GPA         0
Attendance_Percentage         0
Study_Hours_Per_Day           0
Sleep_Hours                   0
Social_Media_Hours            0
Stress_Level                  0
Motivation_Level              0
Discipline_Level              0
Programming_Skill_Level       0
Python_Knowledge              0
Java_Knowledge                0
Database_Knowledge            0
ML_Knowledge                  0
Web_Development_Skill         0
GitHub_Projects_Count         0
Certifications_Count          0
Internship_Experience         0
Internship_Duration_Months    0
Scholarship                   0
Hostel_Resident               0
Financial_Background          0
Transport_Mode                0
Communication_Skill           0
English_Level                 0
Resume_Score                  0
Job_Applications_Submitted    0
Offer_Letters_Received        0
Placement_Status              0
dtype: int64

In [12]:
#Check duplicate rows.
print(data.duplicated())
print("Total Duplicated Values: ",data.duplicated().sum())

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool
Total Duplicated Values:  0

In [13]:
#Remove duplicate rows.
data.drop_duplicates()

,Student_ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
0,1,Female,19,Mardan,CS,5,1056,879,41,2.98,...,Yes,No,High,Bike,4,Good,99,27,2,Placed
1,2,Female,19,Mardan,IT,7,622,973,88,2.84,...,Yes,No,Low,Car,4,Good,38,29,5,Placed
2,3,Female,21,Mardan,DS,2,836,794,64,3.97,...,Yes,Yes,High,Bike,6,Average,81,25,5,Placed
3,4,Female,21,Abbottabad,DS,7,670,860,93,1.73,...,No,No,High,Bus,2,Good,79,43,4,Placed
4,5,Male,19,Peshawar,DS,7,734,1097,94,3.40,...,No,No,Low,Bus,6,Fluent,50,3,1,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Female,18,Abbottabad,AI,2,713,711,60,1.93,...,No,No,Middle,Walk,8,Good,75,39,4,Placed
9996,9997,Male,19,Karachi,IT,8,807,689,33,1.96,...,Yes,No,High,Bus,4,Average,59,13,2,Placed
9997,9998,Female,26,Karachi,ME,6,1085,661,75,2.72,...,Yes,No,Low,Bike,2,Weak,99,47,1,Placed
9998,9999,Female,25,Abbottabad,DS,4,764,718,58,3.88,...,Yes,Yes,High,Walk,7,Average,41,1,5,Placed
9999,10000,Male,21,Karachi,ME,6,1058,835,99,3.20,...,No,No,Middle,Bike,4,Good,58,11,1,Placed

In [14]:
#Fill missing values with mean.
data=data.fillna(data.mean(numeric_only=True))

In [15]:
#Fill missing values with median.
data=data.fillna(data.median(numeric_only=True))

In [16]:
#Fill missing values with mode.
data=data.fillna(data.mode(numeric_only=True))

In [17]:
#Drop rows with missing values.
data.dropna(how='all')

,Student_ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
0,1,Female,19,Mardan,CS,5,1056,879,41,2.98,...,Yes,No,High,Bike,4,Good,99,27,2,Placed
1,2,Female,19,Mardan,IT,7,622,973,88,2.84,...,Yes,No,Low,Car,4,Good,38,29,5,Placed
2,3,Female,21,Mardan,DS,2,836,794,64,3.97,...,Yes,Yes,High,Bike,6,Average,81,25,5,Placed
3,4,Female,21,Abbottabad,DS,7,670,860,93,1.73,...,No,No,High,Bus,2,Good,79,43,4,Placed
4,5,Male,19,Peshawar,DS,7,734,1097,94,3.40,...,No,No,Low,Bus,6,Fluent,50,3,1,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Female,18,Abbottabad,AI,2,713,711,60,1.93,...,No,No,Middle,Walk,8,Good,75,39,4,Placed
9996,9997,Male,19,Karachi,IT,8,807,689,33,1.96,...,Yes,No,High,Bus,4,Average,59,13,2,Placed
9997,9998,Female,26,Karachi,ME,6,1085,661,75,2.72,...,Yes,No,Low,Bike,2,Weak,99,47,1,Placed
9998,9999,Female,25,Abbottabad,DS,4,764,718,58,3.88,...,Yes,Yes,High,Walk,7,Average,41,1,5,Placed
9999,10000,Male,21,Karachi,ME,6,1058,835,99,3.20,...,No,No,Middle,Bike,4,Good,58,11,1,Placed

In [18]:
#Rename dataset columns.
data=data.rename(columns={'Student_ID':'ID'})
data.head()

,ID,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
0,1,Female,19,Mardan,CS,5,1056,879,41,2.98,...,Yes,No,High,Bike,4,Good,99,27,2,Placed
1,2,Female,19,Mardan,IT,7,622,973,88,2.84,...,Yes,No,Low,Car,4,Good,38,29,5,Placed
2,3,Female,21,Mardan,DS,2,836,794,64,3.97,...,Yes,Yes,High,Bike,6,Average,81,25,5,Placed
3,4,Female,21,Abbottabad,DS,7,670,860,93,1.73,...,No,No,High,Bus,2,Good,79,43,4,Placed
4,5,Male,19,Peshawar,DS,7,734,1097,94,3.40,...,No,No,Low,Bus,6,Fluent,50,3,1,Placed

In [19]:
#Convert datatype of columns.
data['Semester'].astype('str')
data['Semester'].dtype

dtype('int64')

In [20]:
#Remove unwanted columns.
df=data.drop(columns='ID')

In [21]:
#Detect outliers using IQR method.
Q1=df['Age'].quantile(0.25)
Q3=df['Age'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR
print(f"Lower: {lower}\nUpper: {upper}")

Lower: 14.0
Upper: 30.0

In [22]:
#Remove outliers from dataset.
d=df[(df['Age']>=lower)&(df['Age']<=upper)]

In [23]:
#Find average marks from dataset.
df['Matric_Marks'].mean()

np.float64(846.3021)

In [24]:
#Find highest and lowest values.
lowest=df['Matric_Marks'].min()
highest=df['Matric_Marks'].max()
print(f"Lowest Marks: {lowest}\nHighest: {highest}")

Lowest Marks: 600
Highest: 1100

In [25]:
#Count unique values in column.
print(df['Gender'].unique())

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [26]:
#Find correlation between columns.
print(df['Matric_Marks'].corr(df['Intermediate_Marks']))

-0.0011950371631290313

In [27]:
#Group data using groupby().
print(df.groupby('Communication_Skill')['Current_CGPA'].mean())

Communication_Skill
1     2.771483
2     2.711935
3     2.733044
4     2.725579
5     2.719363
6     2.739576
7     2.770991
8     2.727540
9     2.746616
10    2.773457
Name: Current_CGPA, dtype: float64

In [28]:
#Analyze department-wise Communication_Skill.
print(df.groupby('Department')['Communication_Skill'].mean())

Department
AI     5.454086
BBA    5.455364
CS     5.478632
DS     5.564837
EE     5.439655
IT     5.398112
ME     5.465388
SE     5.490783
Name: Communication_Skill, dtype: float64

In [29]:
#Analyze gender distribution.
df['Gender'].value_counts()

Gender
Male      5004
Female    4996
Name: count, dtype: int64

In [30]:
#Find top 10 highest values.
#Sort dataset based on column.
data2=df.sort_values('Current_CGPA',ascending=True)
data2.iloc[-11:-1,:]

,Gender,Age,City,Department,Semester,Matric_Marks,Intermediate_Marks,Entry_Test_Score,Current_CGPA,Previous_Semester_GPA,...,Scholarship,Hostel_Resident,Financial_Background,Transport_Mode,Communication_Skill,English_Level,Resume_Score,Job_Applications_Submitted,Offer_Letters_Received,Placement_Status
1146,Male,18,Karachi,AI,3,645,878,54,4.0,4.00,...,No,No,High,Bike,5,Good,32,20,2,Placed
6710,Female,23,Mardan,SE,1,1088,740,53,4.0,4.00,...,Yes,Yes,High,Bike,8,Average,96,13,4,Placed
9764,Female,20,Abbottabad,DS,8,803,853,92,4.0,4.00,...,No,Yes,High,Bus,4,Fluent,81,30,1,Placed
5460,Female,25,Mardan,ME,2,685,601,34,4.0,3.72,...,Yes,Yes,High,Bus,4,Good,59,44,1,Placed
1567,Female,25,Mardan,EE,6,1082,1090,78,4.0,3.91,...,Yes,No,Low,Walk,5,Weak,69,17,1,Placed
7426,Male,18,Abbottabad,EE,6,830,600,32,4.0,3.86,...,No,Yes,Low,Bike,7,Fluent,52,23,3,Placed
3485,Female,21,Lahore,IT,7,936,716,43,4.0,3.67,...,No,No,Middle,Bus,9,Fluent,38,49,0,Placed
3199,Female,25,Karachi,AI,7,713,775,99,4.0,4.00,...,No,Yes,High,Car,3,Average,73,9,4,Placed
3799,Female,19,Karachi,CS,2,914,914,85,4.0,4.00,...,No,No,Middle,Bike,9,Weak,48,36,0,Placed
6200,Female,20,Islamabad,CS,6,618,844,96,4.0,3.87,...,No,Yes,Low,Bike,4,Weak,99,47,2,Placed

In [36]:
#Find most frequent category.
df['City'].mode()

0    Peshawar
Name: City, dtype: str