In [1]:
import pandas as pd

In [2]:
#Create a Pandas Series from list.
list1=[1,2,"a",4,5.7,6,"7"]
d=pd.Series(list1)
d

0      1
1      2
2      a
3      4
4    5.7
5      6
6      7
dtype: object

In [3]:
#Create a DataFrame from dictionary.
dict={
    "name":['Aslam','Ali','Usama','Abid','John','Kashif','Ameen','Bilal','Khizer','Usama','Ali'],
    "age":[20,21,21,23,21,19,19,24,23,20,21],
    "semester":[2,3,4,5,3,1,1,8,7,3,3]
}
de=pd.DataFrame(dict)
de

      name  age  semester
0    Aslam   20         2
1      Ali   21         3
2    Usama   21         4
3     Abid   23         5
4     John   21         3
5   Kashif   19         1
6    Ameen   19         1
7    Bilal   24         8
8   Khizer   23         7
9    Usama   20         3
10     Ali   21         3

In [4]:
#Display first 5 rows using head().
de.head()

    name  age  semester
0  Aslam   20         2
1    Ali   21         3
2  Usama   21         4
3   Abid   23         5
4   John   21         3

In [5]:
#Display last 5 rows using tail().
de.tail()

      name  age  semester
6    Ameen   19         1
7    Bilal   24         8
8   Khizer   23         7
9    Usama   20         3
10     Ali   21         3

In [6]:
#Check shape of DataFrame.
de.shape

(11, 3)

In [7]:
#Print column names of DataFrame.
de.columns

Index(['name', 'age', 'semester'], dtype='str')

In [8]:
#Select single column from DataFrame.
de.name

0      Aslam
1        Ali
2      Usama
3       Abid
4       John
5     Kashif
6      Ameen
7      Bilal
8     Khizer
9      Usama
10       Ali
Name: name, dtype: str

In [9]:
#Select multiple columns from DataFrame.
de[['name','semester']]

      name  semester
0    Aslam         2
1      Ali         3
2    Usama         4
3     Abid         5
4     John         3
5   Kashif         1
6    Ameen         1
7    Bilal         8
8   Khizer         7
9    Usama         3
10     Ali         3

In [10]:
#Add new column into DataFrame.
de['GPA']=[3.2,2.9,3.3,3.0,4.0,3.7,3.6,3.92,2.98,3.54,2.9]
de

      name  age  semester   GPA
0    Aslam   20         2  3.20
1      Ali   21         3  2.90
2    Usama   21         4  3.30
3     Abid   23         5  3.00
4     John   21         3  4.00
5   Kashif   19         1  3.70
6    Ameen   19         1  3.60
7    Bilal   24         8  3.92
8   Khizer   23         7  2.98
9    Usama   20         3  3.54
10     Ali   21         3  2.90

In [11]:
#Delete a column from DataFrame.
df=de.drop(columns='age')
df

      name  semester   GPA
0    Aslam         2  3.20
1      Ali         3  2.90
2    Usama         4  3.30
3     Abid         5  3.00
4     John         3  4.00
5   Kashif         1  3.70
6    Ameen         1  3.60
7    Bilal         8  3.92
8   Khizer         7  2.98
9    Usama         3  3.54
10     Ali         3  2.90

In [12]:
#Rename column names.
de.rename(columns={'age':'AGE'})

      name  AGE  semester   GPA
0    Aslam   20         2  3.20
1      Ali   21         3  2.90
2    Usama   21         4  3.30
3     Abid   23         5  3.00
4     John   21         3  4.00
5   Kashif   19         1  3.70
6    Ameen   19         1  3.60
7    Bilal   24         8  3.92
8   Khizer   23         7  2.98
9    Usama   20         3  3.54
10     Ali   21         3  2.90

In [13]:
#Find summary statistics using describe().
de.describe()

             age   semester        GPA
count  11.000000  11.000000  11.000000
mean   21.090909   3.636364   3.367273
std     1.640399   2.248232   0.406770
min    19.000000   1.000000   2.900000
25%    20.000000   2.500000   2.990000
50%    21.000000   3.000000   3.300000
75%    22.000000   4.500000   3.650000
max    24.000000   8.000000   4.000000

In [14]:
#Check missing values in DataFrame.
de['marks']=[20,21,None,25,22,None,17,None,12,15,21]
de.isnull()

     name    age  semester    GPA  marks
0   False  False     False  False  False
1   False  False     False  False  False
2   False  False     False  False   True
3   False  False     False  False  False
4   False  False     False  False  False
5   False  False     False  False   True
6   False  False     False  False  False
7   False  False     False  False   True
8   False  False     False  False  False
9   False  False     False  False  False
10  False  False     False  False  False

In [15]:
#Fill missing values using fillna().
df=de.fillna(de['marks'].mean())
df['marks']=df['marks'].astype(int)
df

      name  age  semester   GPA  marks
0    Aslam   20         2  3.20     20
1      Ali   21         3  2.90     21
2    Usama   21         4  3.30     19
3     Abid   23         5  3.00     25
4     John   21         3  4.00     22
5   Kashif   19         1  3.70     19
6    Ameen   19         1  3.60     17
7    Bilal   24         8  3.92     19
8   Khizer   23         7  2.98     12
9    Usama   20         3  3.54     15
10     Ali   21         3  2.90     21

In [16]:
#Drop rows with missing values.
de2=de.dropna()
de2

      name  age  semester   GPA  marks
0    Aslam   20         2  3.20   20.0
1      Ali   21         3  2.90   21.0
3     Abid   23         5  3.00   25.0
4     John   21         3  4.00   22.0
6    Ameen   19         1  3.60   17.0
8   Khizer   23         7  2.98   12.0
9    Usama   20         3  3.54   15.0
10     Ali   21         3  2.90   21.0

In [17]:
#Count total null values in each column.
de.isnull().sum()

name        0
age         0
semester    0
GPA         0
marks       3
dtype: int64

In [18]:
#Find maximum value in a column.
print("MAximum value in each column : \n ------\n",df.max())#all columns
print('MAximum value in a column : \n ------\n',"Maximum MArks: ",de['marks'].max())
print('\n','\n')
#Find minimum value in a column.
print('Minimum value in each column : \n ------\n',de.min())
print('Minimum value in a column : \n ------\n',"Minimum MArks: ",de['marks'].min())

MAximum value in each column :
 ------
 name        Usama
age            24
semester        8
GPA           4.0
marks          25
dtype: object
MAximum value in a column :
 ------
 Maximum MArks:  25.0



Minimum value in each column :
 ------
 name        Abid
age           19
semester       1
GPA          2.9
marks       12.0
dtype: object
Minimum value in a column :
 ------
 Minimum MArks:  12.0

In [19]:
#Find average of a column.
print("Average age: ",df['age'].mean())
#Filter rows where age is greater than 18.
print(df[df['age']>20])
#Filter rows using multiple conditions.
print("\n The Topper students list with more than 3 gpa: \n----------------------\n")
print(df[(df['age']>20)&(df['GPA']>3)])

Average age:  21.09090909090909
      name  age  semester   GPA  marks
1      Ali   21         3  2.90     21
2    Usama   21         4  3.30     19
3     Abid   23         5  3.00     25
4     John   21         3  4.00     22
7    Bilal   24         8  3.92     19
8   Khizer   23         7  2.98     12
10     Ali   21         3  2.90     21

 The Topper students list with more than 3 gpa:
----------------------

    name  age  semester   GPA  marks
2  Usama   21         4  3.30     19
4   John   21         3  4.00     22
7  Bilal   24         8  3.92     19

In [ ]:
#Sort DataFrame by one column.
d=df.sort_values(by='semester')
#print(d)
#Sort DataFrame by multiple columns.
d=df.sort_values(by=['marks','semester'])
#Find duplicate rows.
df[df.duplicated()]
#Remove duplicate rows.
df.drop_duplicates()
#Count unique values in a column.
df['age'].unique()
#Convert column datatype.
df['marks']=df['marks'].astype(float)
df
#Save DataFrame into CSV file.
df.to_csv('data.csv')
#Create DataFrame from CSV file.
data2=pd.read_csv('data.csv')
data=data2.drop(columns='Unnamed: 0')
data

0      Aslam
1        Ali
2      Usama
3       Abid
4       John
5     Kashif
6      Ameen
7      Bilal
8     Khizer
9      Usama
10       Ali
Name: name, dtype: str

      name  age  semester   GPA  marks
0    Aslam   20         2  3.20   20.0
1      Ali   21         3  2.90   21.0
2    Usama   21         4  3.30   19.0
3     Abid   23         5  3.00   25.0
4     John   21         3  4.00   22.0
5   Kashif   19         1  3.70   19.0
6    Ameen   19         1  3.60   17.0
7    Bilal   24         8  3.92   19.0
8   Khizer   23         7  2.98   12.0
9    Usama   20         3  3.54   15.0
10     Ali   21         3  2.90   21.0

In [33]:
#Apply function on column using apply().
print(df['name'].apply(lambda x: x.capitalize()))
def categorize_age(age):
    if age < 21:
        return 'Junior'
    else:
        return 'Senior'
# Apply the function to create a new column
df['Seniority'] = df['age'].apply(categorize_age)
print(df)

0      Aslam
1        Ali
2      Usama
3       Abid
4       John
5     Kashif
6      Ameen
7      Bilal
8     Khizer
9      Usama
10       Ali
Name: name, dtype: str
      name  age  semester   GPA  marks Seniority
0    Aslam   20         2  3.20   20.0    Junior
1      Ali   21         3  2.90   21.0    Senior
2    Usama   21         4  3.30   19.0    Senior
3     Abid   23         5  3.00   25.0    Senior
4     John   21         3  4.00   22.0    Senior
5   Kashif   19         1  3.70   19.0    Junior
6    Ameen   19         1  3.60   17.0    Junior
7    Bilal   24         8  3.92   19.0    Senior
8   Khizer   23         7  2.98   12.0    Senior
9    Usama   20         3  3.54   15.0    Junior
10     Ali   21         3  2.90   21.0    Senior

In [43]:
#Merge two DataFrames.
da=pd.merge(d,df, on='name')
da

,name,age_x,semester_x,GPA_x,marks_x,age_y,semester_y,GPA_y,marks_y,Seniority
0,Khizer,23,7,2.98,12.0,23,7,2.98,12.0,Senior
1,Usama,20,3,3.54,15.0,21,4,3.30,19.0,Senior
2,Usama,20,3,3.54,15.0,20,3,3.54,15.0,Junior
3,Ameen,19,1,3.60,17.0,19,1,3.60,17.0,Junior
4,Kashif,19,1,3.70,19.0,19,1,3.70,19.0,Junior
5,Usama,21,4,3.30,19.0,21,4,3.30,19.0,Senior
6,Usama,21,4,3.30,19.0,20,3,3.54,15.0,Junior
7,Bilal,24,8,3.92,19.0,24,8,3.92,19.0,Senior
8,Aslam,20,2,3.20,20.0,20,2,3.20,20.0,Junior
9,Ali,21,3,2.90,21.0,21,3,2.90,21.0,Senior
10,Ali,21,3,2.90,21.0,21,3,2.90,21.0,Senior
11,Ali,21,3,2.90,21.0,21,3,2.90,21.0,Senior
12,Ali,21,3,2.90,21.0,21,3,2.90,21.0,Senior
13,John,21,3,4.00,22.0,21,3,4.00,22.0,Senior
14,Abid,23,5,3.00,25.0,23,5,3.00,25.0,Senior

In [45]:
#Access rows using loc[].
df.loc[1:5,"name":"semester"]
#Access rows using iloc[].
df.iloc[1:6,0:2]

     name  age
1     Ali   21
2   Usama   21
3    Abid   23
4    John   21
5  Kashif   19